get_world_offset = """
return vec2f(0., 0.);
"""

get_fragment_color = """
return scene_instance.temp_vec4_var * textureSample(color_tex, sampler_color_tex, uv0.xy);"""

[uniform_types]
color_param_1 = "vec4f"
temp_vec4_var = { type = "vec4f", default = [1.0, 1.0, 1.0, 1.0] }

[texture_descs]
color_tex = "linear"
